"""
Rich vocabulary seed script.

Populates the `vocabulary` table with premium learning data:
pronunciation, part of speech, difficulty, category, synonyms, antonyms,
AI tips, and usage examples.

Idempotent: existing words (matched by lowercased word) are updated with
the new rich fields; new words are inserted.
"""
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from database import SessionLocal
from models_vocabulary import Vocabulary

WORDS = [
    # ---------------- Beginner ----------------
    {
        "word": "Apple",
        "pronunciation": "/ˈæp.əl/",
        "part_of_speech": "noun",
        "meaning": "A round fruit with red, green, or yellow skin and a sweet taste.",
        "example": "I eat an apple every morning.",
        "example2": "She bought three apples from the market.",
        "synonyms": "fruit, pome",
        "antonyms": "",
        "ai_tip": "Use 'apple' for the fruit or the company. Add 'an' before it because it starts with a vowel sound.",
        "common_mistakes": "Saying 'a apple' instead of 'an apple'.",
        "when_to_use": "When talking about the fruit or the technology brand.",
        "when_not_to_use": "Don't use it as a general word for all fruits.",
        "natural_sentence": "Want an apple? They're really sweet today.",
        "formal_sentence": "Apples are a rich source of dietary fiber.",
        "informal_sentence": "Grab an apple on your way out!",
        "difficulty": "Beginner",
        "category": "Daily Life",
        "xp_reward": 10,
    },
    {
        "word": "Beautiful",
        "pronunciation": "/ˈbjuː.tɪ.fəl/",
        "part_of_speech": "adjective",
        "meaning": "Pleasing to the senses; very attractive or lovely.",
        "example": "The garden is beautiful in spring.",
        "example2": "She wore a beautiful dress to the party.",
        "synonyms": "lovely, gorgeous, stunning, pretty",
        "antonyms": "ugly, unattractive",
        "ai_tip": "'Beautiful' describes appearance or experience. For people, 'handsome' is often used for men.",
        "common_mistakes": "Spelling it as 'beautifull' with double 'l'.",
        "when_to_use": "To describe something visually or emotionally pleasing.",
        "when_not_to_use": "Avoid overusing it; try specific words like 'elegant' or 'breathtaking'.",
        "natural_sentence": "That sunset is absolutely beautiful.",
        "formal_sentence": "The architecture of the building is quite beautiful.",
        "informal_sentence": "Wow, you look beautiful tonight!",
        "difficulty": "Beginner",
        "category": "Emotions",
        "xp_reward": 10,
    },
    {
        "word": "Learn",
        "pronunciation": "/lɜːn/",
        "part_of_speech": "verb",
        "meaning": "To gain knowledge or skill through study, experience, or practice.",
        "example": "We learn English every day.",
        "example2": "Children learn quickly when they are curious.",
        "synonyms": "study, acquire, master",
        "antonyms": "forget, ignore",
        "ai_tip": "'Learn' is irregular: learn/learned or learnt (British). Pair it with 'about' or 'how to'.",
        "common_mistakes": "Saying 'learn to him' instead of 'learn from him'.",
        "when_to_use": "When acquiring new knowledge or a skill.",
        "when_not_to_use": "Don't confuse with 'teach' — you teach someone, you learn from someone.",
        "natural_sentence": "I'm learning how to cook.",
        "formal_sentence": "Students learn best through consistent practice.",
        "informal_sentence": "Let's learn a new song together!",
        "difficulty": "Beginner",
        "category": "Education",
        "xp_reward": 10,
    },
    {
        "word": "Happy",
        "pronunciation": "/ˈhæp.i/",
        "part_of_speech": "adjective",
        "meaning": "Feeling or showing pleasure, contentment, or joy.",
        "example": "I am happy today because the sun is shining.",
        "example2": "The happy children played in the park.",
        "synonyms": "joyful, cheerful, glad, delighted",
        "antonyms": "sad, unhappy, miserable",
        "ai_tip": "'Happy' is a general emotion. Use 'glad' for relief and 'delighted' for strong joy.",
        "common_mistakes": "Confusing 'happy' with 'lucky' in some languages.",
        "when_to_use": "To express a positive emotional state.",
        "when_not_to_use": "Don't use it for temporary excitement; use 'excited' instead.",
        "natural_sentence": "I'm so happy you came!",
        "formal_sentence": "We are happy to announce the new policy.",
        "informal_sentence": "She's super happy with her new phone.",
        "difficulty": "Beginner",
        "category": "Emotions",
        "xp_reward": 10,
    },
    {
        "word": "Book",
        "pronunciation": "/bʊk/",
        "part_of_speech": "noun",
        "meaning": "A set of printed or digital pages bound together for reading.",
        "example": "She is reading a book about history.",
        "example2": "I need to book a table at the restaurant.",
        "synonyms": "volume, publication, reserve",
        "antonyms": "",
        "ai_tip": "'Book' is also a verb meaning 'to reserve'. Context tells you which meaning applies.",
        "common_mistakes": "Forgetting that 'book' can be a verb (to reserve).",
        "when_to_use": "As a noun for reading material; as a verb for reserving.",
        "when_not_to_use": "Don't use 'book' for magazines or newspapers.",
        "natural_sentence": "Can you book a flight for me?",
        "formal_sentence": "I would like to book an appointment.",
        "informal_sentence": "I booked us a table for seven.",
        "difficulty": "Beginner",
        "category": "Education",
        "xp_reward": 10,
    },
    # ---------------- Intermediate ----------------
    {
        "word": "Ambitious",
        "pronunciation": "/æmˈbɪʃ.əs/",
        "part_of_speech": "adjective",
        "meaning": "Having a strong desire and determination to achieve success.",
        "example": "She is ambitious and studies every day.",
        "example2": "It was an ambitious project, but they finished it.",
        "synonyms": "driven, determined, motivated, aspiring",
        "antonyms": "lazy, unmotivated, indifferent",
        "ai_tip": "Use 'ambitious' for goals and careers. It carries a positive tone in professional contexts.",
        "common_mistakes": "Confusing 'ambitious' with 'anxious'.",
        "when_to_use": "To describe someone with high goals or a challenging plan.",
        "when_not_to_use": "Avoid using it negatively to mean 'greedy'.",
        "natural_sentence": "He's really ambitious — he wants to run his own company.",
        "formal_sentence": "The candidate presented an ambitious development plan.",
        "informal_sentence": "That's an ambitious goal, but go for it!",
        "difficulty": "Intermediate",
        "category": "Business",
        "xp_reward": 15,
    },
    {
        "word": "Reserve",
        "pronunciation": "/rɪˈzɜːv/",
        "part_of_speech": "verb",
        "meaning": "To keep something for future use or to book something in advance.",
        "example": "I'd like to reserve a table for two.",
        "example2": "They reserved the conference room for Monday.",
        "synonyms": "book, set aside, retain",
        "antonyms": "cancel, release",
        "ai_tip": "'Reserve' is more formal than 'book'. Use it in restaurants, hotels, and business.",
        "common_mistakes": "Saying 'reserve to' instead of 'reserve for'.",
        "when_to_use": "When booking or setting something aside in advance.",
        "when_not_to_use": "Don't use it for casual plans; 'book' is friendlier.",
        "natural_sentence": "Let me reserve a spot for us.",
        "formal_sentence": "We have reserved a suite for your stay.",
        "informal_sentence": "I reserved us seats near the stage.",
        "difficulty": "Intermediate",
        "category": "Restaurant",
        "xp_reward": 15,
    },
    {
        "word": "Journey",
        "pronunciation": "/ˈdʒɜː.ni/",
        "part_of_speech": "noun",
        "meaning": "The act of traveling from one place to another, often over a long distance.",
        "example": "The journey to the mountains took five hours.",
        "example2": "Her learning journey has been remarkable.",
        "synonyms": "trip, voyage, expedition, travels",
        "antonyms": "",
        "ai_tip": "'Journey' can be literal (travel) or figurative (personal growth).",
        "common_mistakes": "Using 'journey' for very short trips; 'trip' is better there.",
        "when_to_use": "For long or meaningful travel and personal development.",
        "when_not_to_use": "Don't use it for a quick errand.",
        "natural_sentence": "It's a long journey, so let's leave early.",
        "formal_sentence": "The journey toward fluency requires dedication.",
        "informal_sentence": "What a journey that was!",
        "difficulty": "Intermediate",
        "category": "Travel",
        "xp_reward": 15,
    },
    {
        "word": "Confident",
        "pronunciation": "/ˈkɒn.fɪ.dənt/",
        "part_of_speech": "adjective",
        "meaning": "Feeling sure about one's abilities or qualities.",
        "example": "She felt confident before the interview.",
        "example2": "He gave a confident presentation.",
        "synonyms": "self-assured, poised, certain",
        "antonyms": "unsure, hesitant, timid",
        "ai_tip": "'Confident' (adjective) vs 'confidant' (noun, a trusted person). Watch the spelling.",
        "common_mistakes": "Spelling it 'confidant' when used as an adjective.",
        "when_to_use": "To describe self-assurance in ability or decisions.",
        "when_not_to_use": "Don't confuse with 'arrogant', which is negative.",
        "natural_sentence": "I'm confident we'll win this game.",
        "formal_sentence": "The team is confident in the new strategy.",
        "informal_sentence": "She walked in looking super confident.",
        "difficulty": "Intermediate",
        "category": "Emotions",
        "xp_reward": 15,
    },
    {
        "word": "Symptom",
        "pronunciation": "/ˈsɪmp.təm/",
        "part_of_speech": "noun",
        "meaning": "A physical or mental sign that indicates a condition or illness.",
        "example": "A fever is a common symptom of the flu.",
        "example2": "Fatigue can be a symptom of stress.",
        "synonyms": "sign, indication, manifestation",
        "antonyms": "",
        "ai_tip": "Use 'symptom' in medical contexts; 'sign' is more general.",
        "common_mistakes": "Confusing 'symptom' with 'cause'.",
        "when_to_use": "When describing evidence of a health condition.",
        "when_not_to_use": "Don't use it for general observations; use 'sign'.",
        "natural_sentence": "What are your symptoms?",
        "formal_sentence": "The patient reported several symptoms of infection.",
        "informal_sentence": "My only symptom is a sore throat.",
        "difficulty": "Intermediate",
        "category": "Health",
        "xp_reward": 15,
    },
    # ---------------- Advanced ----------------
    {
        "word": "Eloquent",
        "pronunciation": "/ˈel.ə.kwənt/",
        "part_of_speech": "adjective",
        "meaning": "Fluent and persuasive in speaking or writing; clearly expressing ideas.",
        "example": "She gave an eloquent speech that moved the audience.",
        "example2": "His eloquent writing style won many readers.",
        "synonyms": "articulate, fluent, expressive, persuasive",
        "antonyms": "inarticulate, halting, clumsy",
        "ai_tip": "'Eloquent' praises clear, moving communication. Use it for speeches and writing.",
        "common_mistakes": "Pronouncing it as 'e-lo-quent' (it's 'el-uh-kwunt').",
        "when_to_use": "To praise expressive, persuasive language.",
        "when_not_to_use": "Don't use it for simple, plain speech.",
        "natural_sentence": "That was an eloquent way to put it.",
        "formal_sentence": "The ambassador delivered an eloquent address.",
        "informal_sentence": "She's so eloquent — everything she says sounds poetic.",
        "difficulty": "Advanced",
        "category": "Education",
        "xp_reward": 25,
    },
    {
        "word": "Resilient",
        "pronunciation": "/rɪˈzɪl.i.ənt/",
        "part_of_speech": "adjective",
        "meaning": "Able to recover quickly from difficulties or setbacks.",
        "example": "Children are often remarkably resilient.",
        "example2": "The resilient economy bounced back within a year.",
        "synonyms": "tough, adaptable, strong, durable",
        "antonyms": "fragile, vulnerable, weak",
        "ai_tip": "'Resilient' describes people, systems, or materials that recover from stress.",
        "common_mistakes": "Confusing 'resilient' with 'resistant' (resistant prevents, resilient recovers).",
        "when_to_use": "For people or systems that bounce back from hardship.",
        "when_not_to_use": "Don't use it for things that simply avoid damage.",
        "natural_sentence": "She's resilient — nothing keeps her down for long.",
        "formal_sentence": "The organization proved resilient during the crisis.",
        "informal_sentence": "Wow, you're so resilient after all that!",
        "difficulty": "Advanced",
        "category": "Business",
        "xp_reward": 25,
    },
    {
        "word": "Ubiquitous",
        "pronunciation": "/juːˈbɪk.wɪ.təs/",
        "part_of_speech": "adjective",
        "meaning": "Present, appearing, or found everywhere at the same time.",
        "example": "Smartphones have become ubiquitous in modern life.",
        "example2": "Coffee shops are ubiquitous in this city.",
        "synonyms": "omnipresent, pervasive, everywhere",
        "antonyms": "rare, scarce, absent",
        "ai_tip": "'Ubiquitous' is formal and advanced. Use it to describe things that are everywhere.",
        "common_mistakes": "Mispronouncing as 'you-bi-quit-us' (it's 'yoo-bik-wi-tus').",
        "when_to_use": "For things that seem to be everywhere.",
        "when_not_to_use": "Don't use it for merely common things; it implies near-universal presence.",
        "natural_sentence": "Those ads are ubiquitous lately.",
        "formal_sentence": "The technology has become ubiquitous across industries.",
        "informal_sentence": "Fast food is pretty much ubiquitous now.",
        "difficulty": "Advanced",
        "category": "Technology",
        "xp_reward": 25,
    },
    {
        "word": "Pragmatic",
        "pronunciation": "/præɡˈmæt.ɪk/",
        "part_of_speech": "adjective",
        "meaning": "Dealing with things sensibly and realistically, based on practical considerations.",
        "example": "We need a pragmatic approach to this problem.",
        "example2": "Her pragmatic decisions saved the company money.",
        "synonyms": "practical, realistic, sensible",
        "antonyms": "idealistic, impractical, theoretical",
        "ai_tip": "'Pragmatic' values results over theory. Common in business and politics.",
        "common_mistakes": "Confusing 'pragmatic' with 'dogmatic' (stubborn about beliefs).",
        "when_to_use": "When favoring practical, results-driven solutions.",
        "when_not_to_use": "Don't use it when idealism or vision is the focus.",
        "natural_sentence": "Let's be pragmatic about the budget.",
        "formal_sentence": "The committee adopted a pragmatic strategy.",
        "informal_sentence": "I'm being pragmatic — we just can't afford it.",
        "difficulty": "Advanced",
        "category": "Business",
        "xp_reward": 25,
    },
    {
        "word": "Empathy",
        "pronunciation": "/ˈem.pə.θi/",
        "part_of_speech": "noun",
        "meaning": "The ability to understand and share the feelings of another person.",
        "example": "Good leaders show empathy toward their team.",
        "example2": "Her empathy made her a wonderful counselor.",
        "synonyms": "compassion, understanding, sensitivity",
        "antonyms": "indifference, coldness, apathy",
        "ai_tip": "'Empathy' is feeling with someone; 'sympathy' is feeling for someone.",
        "common_mistakes": "Mixing up 'empathy' and 'sympathy'.",
        "when_to_use": "When describing deep emotional understanding of others.",
        "when_not_to_use": "Don't use it for simple pity.",
        "natural_sentence": "It takes empathy to really help someone.",
        "formal_sentence": "Empathy is essential in patient care.",
        "informal_sentence": "She has so much empathy for animals.",
        "difficulty": "Advanced",
        "category": "Emotions",
        "xp_reward": 25,
    },
    # ---------------- More categories ----------------
    {
        "word": "Itinerary",
        "pronunciation": "/aɪˈtɪn.ə.rər.i/",
        "part_of_speech": "noun",
        "meaning": "A planned route or schedule for a journey.",
        "example": "Our itinerary includes three cities in a week.",
        "example2": "Please share the travel itinerary with the team.",
        "synonyms": "schedule, plan, route, timetable",
        "antonyms": "",
        "ai_tip": "'Itinerary' is common in travel planning. Pronounce it carefully.",
        "common_mistakes": "Spelling it 'itinery' or 'itinirary'.",
        "when_to_use": "When describing a travel plan or schedule.",
        "when_not_to_use": "Don't use it for daily to-do lists.",
        "natural_sentence": "What's on the itinerary for tomorrow?",
        "formal_sentence": "The itinerary has been finalized for your trip.",
        "informal_sentence": "Our itinerary is packed but fun!",
        "difficulty": "Intermediate",
        "category": "Travel",
        "xp_reward": 15,
    },
    {
        "word": "Delicious",
        "pronunciation": "/dɪˈlɪʃ.əs/",
        "part_of_speech": "adjective",
        "meaning": "Having a very pleasant taste or smell.",
        "example": "This soup is delicious!",
        "example2": "She baked a delicious chocolate cake.",
        "synonyms": "tasty, flavorful, scrumptious, delectable",
        "antonyms": "bland, tasteless, disgusting",
        "ai_tip": "'Delicious' is the go-to word for great-tasting food.",
        "common_mistakes": "Spelling it 'delicous' (missing the 'i').",
        "when_to_use": "To praise the taste or smell of food.",
        "when_not_to_use": "Don't use it for non-food items.",
        "natural_sentence": "Mmm, this is delicious!",
        "formal_sentence": "The chef prepared a delicious three-course meal.",
        "informal_sentence": "That burger was seriously delicious.",
        "difficulty": "Beginner",
        "category": "Restaurant",
        "xp_reward": 10,
    },
    {
        "word": "Algorithm",
        "pronunciation": "/ˈæl.ɡə.rɪ.ðəm/",
        "part_of_speech": "noun",
        "meaning": "A step-by-step set of instructions to solve a problem or perform a task.",
        "example": "The search algorithm returns results in milliseconds.",
        "example2": "She designed an algorithm to sort the data.",
        "synonyms": "procedure, process, method, formula",
        "antonyms": "",
        "ai_tip": "'Algorithm' is core to computer science. Pronounce the 'th' softly.",
        "common_mistakes": "Pronouncing it 'al-ga-rith-um' instead of 'al-guh-rith-um'.",
        "when_to_use": "In computing, math, and problem-solving contexts.",
        "when_not_to_use": "Don't use it for simple, single-step actions.",
        "natural_sentence": "The algorithm figured out what I like.",
        "formal_sentence": "The team optimized the recommendation algorithm.",
        "informal_sentence": "There's basically an algorithm for everything now.",
        "difficulty": "Advanced",
        "category": "Technology",
        "xp_reward": 25,
    },
    {
        "word": "Grateful",
        "pronunciation": "/ˈɡreɪt.fəl/",
        "part_of_speech": "adjective",
        "meaning": "Feeling or showing thanks for something received or experienced.",
        "example": "I am grateful for your help.",
        "example2": "She felt grateful to have such supportive friends.",
        "synonyms": "thankful, appreciative, obliged",
        "antonyms": "ungrateful, unappreciative",
        "ai_tip": "'Grateful' pairs with 'for' (a thing) or 'to' (a person).",
        "common_mistakes": "Writing 'greatful' instead of 'grateful'.",
        "when_to_use": "To express appreciation or thanks.",
        "when_not_to_use": "Don't confuse with 'gratified' (satisfied).",
        "natural_sentence": "I'm really grateful for your support.",
        "formal_sentence": "We are grateful for your generous contribution.",
        "informal_sentence": "So grateful you could make it!",
        "difficulty": "Intermediate",
        "category": "Emotions",
        "xp_reward": 15,
    },
    {
        "word": "Prescription",
        "pronunciation": "/prɪˈskrɪp.ʃən/",
        "part_of_speech": "noun",
        "meaning": "A written order from a doctor for medicine or treatment.",
        "example": "The doctor gave me a prescription for antibiotics.",
        "example2": "You need a prescription to buy this medicine.",
        "synonyms": "order, authorization, recommendation",
        "antonyms": "",
        "ai_tip": "'Prescription' is medical. 'Description' is a general account of something.",
        "common_mistakes": "Confusing 'prescription' with 'description' or 'subscription'.",
        "when_to_use": "In medical and pharmacy contexts.",
        "when_not_to_use": "Don't use it for general written descriptions.",
        "natural_sentence": "I need to pick up my prescription.",
        "formal_sentence": "The physician issued a prescription for the patient.",
        "informal_sentence": "My prescription's ready at the pharmacy.",
        "difficulty": "Intermediate",
        "category": "Health",
        "xp_reward": 15,
    },
    {
        "word": "Negotiate",
        "pronunciation": "/nɪˈɡoʊ.ʃi.eɪt/",
        "part_of_speech": "verb",
        "meaning": "To discuss with others to reach an agreement.",
        "example": "They will negotiate the contract tomorrow.",
        "example2": "She negotiated a better salary for her new job.",
        "synonyms": "bargain, discuss, arrange, mediate",
        "antonyms": "dictate, impose",
        "ai_tip": "'Negotiate' is key in business. It implies give-and-take to reach agreement.",
        "common_mistakes": "Pronouncing it 'ne-go-she-ate' (it's 'ni-go-shee-ate').",
        "when_to_use": "In business, diplomacy, and conflict resolution.",
        "when_not_to_use": "Don't use it for one-sided decisions.",
        "natural_sentence": "Let's negotiate a fair price.",
        "formal_sentence": "The parties agreed to negotiate a settlement.",
        "informal_sentence": "I negotiated a free upgrade on my flight.",
        "difficulty": "Advanced",
        "category": "Business",
        "xp_reward": 25,
    },
    {
        "word": "Curious",
        "pronunciation": "/ˈkjʊə.ri.əs/",
        "part_of_speech": "adjective",
        "meaning": "Eager to know or learn something; inquisitive.",
        "example": "Children are naturally curious about the world.",
        "example2": "She was curious about how the machine worked.",
        "synonyms": "inquisitive, interested, questioning",
        "antonyms": "indifferent, uninterested, bored",
        "ai_tip": "'Curious' is positive (eager to learn). 'Nosy' is negative (overly intrusive).",
        "common_mistakes": "Confusing 'curious' with 'nosy'.",
        "when_to_use": "To describe a healthy desire to learn or explore.",
        "when_not_to_use": "Don't use it for intrusive snooping.",
        "natural_sentence": "I'm curious — how did you do that?",
        "formal_sentence": "Researchers remain curious about the phenomenon.",
        "informal_sentence": "Curious kids ask the best questions.",
        "difficulty": "Intermediate",
        "category": "Education",
        "xp_reward": 15,
    },
    {
        "word": "Cozy",
        "pronunciation": "/ˈkoʊ.zi/",
        "part_of_speech": "adjective",
        "meaning": "Warm, comfortable, and snug.",
        "example": "The living room feels cozy in winter.",
        "example2": "We found a cozy little café on the corner.",
        "synonyms": "snug, warm, comfortable, inviting",
        "antonyms": "uncomfortable, cold, stark",
        "ai_tip": "'Cozy' describes a warm, comfortable atmosphere. Common for rooms and clothes.",
        "common_mistakes": "Spelling it 'cosy' (British) vs 'cozy' (American) — both are correct.",
        "when_to_use": "For warm, comfortable spaces or feelings.",
        "when_not_to_use": "Don't use it for large, formal spaces.",
        "natural_sentence": "This blanket is so cozy.",
        "formal_sentence": "The inn offers a cozy atmosphere for guests.",
        "informal_sentence": "Let's have a cozy night in.",
        "difficulty": "Beginner",
        "category": "Daily Life",
        "xp_reward": 10,
    },
    {
        "word": "Innovative",
        "pronunciation": "/ˈɪn.ə.veɪ.tɪv/",
        "part_of_speech": "adjective",
        "meaning": "Featuring new methods or ideas; original and creative.",
        "example": "The startup developed an innovative app.",
        "example2": "Her innovative teaching methods engaged every student.",
        "synonyms": "creative, inventive, original, groundbreaking",
        "antonyms": "traditional, conventional, outdated",
        "ai_tip": "'Innovative' praises new, useful ideas. Use it in tech and business.",
        "common_mistakes": "Confusing 'innovative' with 'inventive' (inventive = good at inventing).",
        "when_to_use": "To describe new, creative solutions or products.",
        "when_not_to_use": "Don't use it for small improvements; use 'improved'.",
        "natural_sentence": "That's a really innovative idea.",
        "formal_sentence": "The company is known for its innovative designs.",
        "informal_sentence": "Their new feature is super innovative.",
        "difficulty": "Advanced",
        "category": "Technology",
        "xp_reward": 25,
    },
    {
        "word": "Polite",
        "pronunciation": "/pəˈlaɪt/",
        "part_of_speech": "adjective",
        "meaning": "Showing good manners and respect for others.",
        "example": "He is always polite to his teachers.",
        "example2": "She gave a polite smile and left.",
        "synonyms": "courteous, respectful, well-mannered",
        "antonyms": "rude, impolite, disrespectful",
        "ai_tip": "'Polite' is about manners. 'Kind' is about warmth; they often overlap.",
        "common_mistakes": "Confusing 'polite' with 'quiet' (quiet people aren't always polite).",
        "when_to_use": "To describe respectful, well-mannered behavior.",
        "when_not_to_use": "Don't use it for genuine warmth; use 'kind' or 'warm'.",
        "natural_sentence": "Be polite and say thank you.",
        "formal_sentence": "The staff were polite and professional.",
        "informal_sentence": "He's so polite for a kid his age.",
        "difficulty": "Beginner",
        "category": "Daily Life",
        "xp_reward": 10,
    },
]


def main():
    db = SessionLocal()
    try:
        inserted = 0
        updated = 0
        for w in WORDS:
            existing = (
                db.query(Vocabulary)
                .filter(Vocabulary.word.ilike(w["word"]))
                .first()
            )
            if existing:
                for key, value in w.items():
                    setattr(existing, key, value)
                updated += 1
            else:
                db.add(Vocabulary(**w))
                inserted += 1
        db.commit()
        print(f"Seed complete: {inserted} inserted, {updated} updated, {len(WORDS)} total processed.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
